version: '3'

services:

  mariadb:
    image: mariadb
    environment:
      MYSQL_USER: lanets
      MYSQL_PASSWORD: lanets
      MYSQL_DATABASE: lanets
      MYSQL_ROOT_PASSWORD: lanets

  web:
    tty: true
    stdin_open: true
    build: .
    command: |
              bash -c 'bash -s <<EOF
              /opt/django-assets/wait-for-it/wait-for-it.sh --timeout=0 mariadb:3306 && \
              python /opt/django-assets/manage.py migrate && \
              python /opt/django-assets/manage.py runserver 0.0.0.0:8000
              EOF'
    volumes:
      - .:/opt/django-assets
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
