version: '3'

services:
  db:
    image: mongo:3.0.2
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/django-assets
    ports:
      - "8000:8000"
    depends_on:
      - db
